let express=require("express");
let bodyParser=require("body-parser");
let session=require("session");
let cookieParser=require("cookie-parser");
let router=require("../src/routes/route.js");
let conn=require("../db.js");
let app=express();
    app.use(express.static("public"));
    app.set("view engines","ejs");
    app.use(bodyParser.json());
    app.use(express.urlencoded({extended:true}));
    app.use("/",router);
module.exports=app;
